export const ADD_PROJECT = {
  IMAGE: "ADD_PROJECT_IMAGE",
  TEXT: "ADD_PROJECT_TEXT",
};
export const ADD_PROJECT_CONTENT = "ADD_PROJECT_CONTENT";
export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
export const MATCHED_PROJECT = "MATCHED_PROJECT";
export const TRIGGER_MODAL = "TRIGGER_MODAL";
export const CLEAR_VALUES = "CLEAR_VALUES";
export const TOGGLE_EDIT = "TOGGLE_EDIT";
