export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";

export const TOGGLE_MEMBER = "TOGGLE_MEMBER";

export const HANDLE_CHANGE = {
  IMAGE: "ADD_USER_IMAGE",
  TEXT: "ADD_USER_TEXT",
};

export const RESET_LOADING = "RESET_LOADING";